data_file = "Things-to-bench/cosmo_data/C1a.csv"
lambda_op = 1.0e-6
# log_file = "Generated/foo/log.txt"
max_generations = 25
max_time = 60
num_time_steps = 4
op_inventory = "Polynomial"
output-size = 12
output_column = "target"
output_file = "Generated/foo/result.json"
parameter_size = 3
progress_file = "Generated/foo/progress.json"
random_state = 0xbbffef330e3219bc
random_subset_count = 1000
scratch_size = 12
verbosity = 2

