#!/bin/bash
dataset=${1:-d_vdp}
mkdir -p Generated
julia --project=@. -m JessamineBenchmark.AppSimple \
      --data-file "ode-strogatz/$dataset.txt" \
      --op-inventory "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic" \
      --output-size 12 \
      --scratch-size 12 \
      --num-time-steps 3 \
      --max-generations 25 \
      --max-time 7200 \
      --stop-threshold 1.0e-4 \
      --lambda-op 1.0e-6 \
      --output-file "Generated/$dataset.json"
