#!/bin/bash
dataset=d_shearflow1
mkdir -p Generated
julia --project=@. -m JessamineBenchmark.AppSimple \
      --data-file "ode-strogatz/$dataset.txt" \
      --op-inventory "RationalFunction; ExpLog; Trig" \
      --max-time 1800 \
      --output-file "Generated/$dataset.json"
