#!/bin/bash
dataset=d_shearflow1
mkdir -p Generated
julia --project=@. -m JessamineBenchmark.AppSimple \
      --data-file "ode-strogatz/$dataset.txt" \
      --op-inventory "Trig" \
      --output-size 8 \
      --scratch-size 4 \
      --max-time 300 \
      --output-file "Generated/$dataset.json"
