#!/bin/bash
dataset=d_vdp1
mkdir -p Generated
julia --project=@. -m JessamineBenchmark.AppSimple \
      --data-file "ode-strogatz/$dataset.txt" \
      --op-inventory "Polynomial" \
      --stop-threshold 2.0e-9 \
      --max-time 60 \
      --random-state 0xb6500bd3306fd1ca \
      --config-dump-file "Generated/$dataset-config.toml" \
      --progress-file "Generated/$dataset-progress.json" \
      --output-file "Generated/$dataset.json"
