Notes and to-do list for JessamineBenchmark

* Debugging
** Figure out the segfault
See ~stderr-111231.3.txt/Generated/CHT-2026-06-26-1100/C4b/009~
and ~stderr-111231.3.txt/Generated/CHT-2026-06-26-1100/C4b/009~
and ~stderr-111231.3.txt/Generated/CHT-2026-06-26-1100/C4e/001~
and ~stderr-111231.3.txt/Generated/CHT-2026-06-26-1100/C4e/004~
and ~stderr-111231.3.txt/Generated/CHT-2026-06-26-1100/C4e/007~

* Experiments
** DONE SRBench with 50 time steps
CLOSED: [2026-06-29 Mon 09:25]
I think the reason I was getting poor results in Friedman was from using 4 genome time steps.
But I also made several other configuration changes to get
Maybe with 50 time steps, it will have time to search more populations and that spec will yield better performance on other datasets.
** DONE Friedman F1: use random subsets of 100
CLOSED: [2026-06-28 Sun 16:01]
I don't think simultaneously considering all 1000 points in the larger dataset does any good.
Opportunity for an interesting comparison?
** Something that worked for cosmology F8
Run set ~CHT-2026-06-28-2315~ can solve cosmology F8, and F1, F7, sort of F5.
Not F2, though.
Run set ~CHT-2026-06-30-1145~ can solve F8 but still not F2.
** Trying to get cosmology F2 to work
If I narrow things down completely, it will work, see ~CHT-2026-06-30-1245~.
Possibility: Since so many things in Jessamine default to 0, a random multiplicative operation will probably have a 0 somewhere in its operands, so that genome kind of goes nowhere.
** Trying the new random initialization that uses operands only for x and p
In general, the fraction of 15-minute samples that solve each
problem with a rating < 5.0e-7 are way up after this change.
*** [2026-07-01 Wed]From before the change
In Strogatz:
~CHT-2026-06-25-1630~ solved everything
~SRB-2026-06-25-1715-arr8~ and ~arr12~ solved everything but ~shearflow1~
*** After the change
**** In Strogatz:
***** ~CHT-2026-06-25-1630~ still solves everything
bacres, barmag, glider, lv, predprey, vdp: 32/32
shearflow and sfgrid: 25/32 or better
***** DONE ~SRB-2026-06-25-1715-arr12~ solves everything except shearflow1
CLOSED: [2026-07-01 Wed 18:06]
bacres, barmag, glider, lv, vdp, shearflow2, sfgrid2: 32/32
predprey1 19/32, predprey2 16/32
sfgrid1: 1/32
shearflow1: 0/32
***** DONE ~SRB-2026-06-25-1715-arr8~ solves everything except shearflow1
CLOSED: [2026-07-01 Wed 18:07]
bacres, barmag, glider, lv, vdp, shearflow2, sfgrid2: 32/32
predprey1 17/32, predprey2 9/32
sfgrid1 1/32
shearflow1 0/32

**** In cosmology:
Again using 5.0e-7 as the solve threshold
F3 and F6 are lost causes.

I'm disappointed about solving F2.
I really thought changing the initialization would give it the head start to solve F2.

Also, F4 is a polynomial, and I'm disappointed that it's turning out to be hard to solve.
Then again, F4 has \(x^4\), so it takes some fiddling for Jessamine to find it.

***** ~SRB-2026-06-26-1030-arr8~
F1 15/32, F2 1/32, F5 32/32, F7 3/32

***** ~SRB-2026-06-26-1045-arr8~
F1 10/32, F4 1/32, F5 32/32, F7 5/32, F8 1/32

***** ~SRB-2026-06-26-1030-arr12~
only solves F5 and F1 1-ish

***** ~CHT-2026-06-28-2315~
solves F8 13/32, but not F2

* To implement
** DONE Make operation weight configuration available to scikit-learn
CLOSED: [2026-06-28 Sun 16:01]
Challenge: In scikit-learn, you can't pass a dictionary as a configuration argument to a ~Regressor~.
** DONE Make ~setup_samples~ spec-generation faster
CLOSED: [2026-06-28 Sun 16:01]
Now it takes a long time because you have to start a bunch of Julia processes, each of which goes through the loading and compilation process.
** TODO Make config-files able to reference each other
Right now, ~AppSimple~ lets you use --config-file multiple times.
Maybe I should make it so that one config file can load another?
Or I could just do this:
#+BEGIN_SRC sh
AppSimple --config-file <baseline-file> --config-file <collection-specific-file> ...
#+END_SRC
and use the script file as the master source?
** DONE Make AppSimple save a JLD2 file
CLOSED: [2026-07-01 Wed 10:46]
The JSON file is too hard to deserialize.
I may as well make the JSON save file more human-friendly and save the full structure as a different kind of file, and JLD2 looks promising.
** TODO For initial population: Draw operands from inputs & parameters
When making a random initial population, instead of selecting the operand indices uniformly over the entire range, select them from the inputs and parameters.
That might result in fewer situations where the genome computes a bunch of zeros and never gets anywhere.
Put in an option in AppSimple for this.
