output_column = "y"
random_state = 0xa5689970bbe09fc2
num_samples = 32
op_inventory = "Trig"
output-size = 12
scratch_size = 12
parameter_size = 3
num_time_steps = 4
max_generations = 25
max_time = 3600
lambda_op = 1.0e-6
# random_subset_count = 1000
