data_file = "ode-strogatz/d_glider1.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_glider1/016/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_glider1/016/result.json"
parameter_size = 3
progress_file = "Generated/d_glider1/016/progress.json"
random_state = 0x76245794a02547bc
scratch_size = 12
