data_file = "ode-strogatz/d_glider1.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_glider1/013/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_glider1/013/result.json"
progress_file = "Generated/d_glider1/013/progress.json"
random_state = 0xed55caab09a05a59
scratch_size = 12
