data_file = "ode-strogatz/d_lv1.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_lv1/031/log.txt"
max_generations = 25
max_time = 300
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_lv1/031/result.json"
parameter_size = 3
progress_file = "Generated/d_lv1/031/progress.json"
random_state = 0xd331cb7bc502f9b6
scratch_size = 12
