data_file = "ode-strogatz/d_lv1.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_lv1/014/log.txt"
max_generations = 25
max_time = 300
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_lv1/014/result.json"
progress_file = "Generated/d_lv1/014/progress.json"
random_state = 0xbd800d14ac82900f
scratch_size = 12
