data_file = "ode-strogatz/d_lv2.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_lv2/023/log.txt"
max_generations = 25
max_time = 300
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_lv2/023/result.json"
parameter_size = 3
progress_file = "Generated/d_lv2/023/progress.json"
random_state = 0xc4f95fa393dea717
scratch_size = 12
