data_file = "ode-strogatz/d_predprey1.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_predprey1/025/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_predprey1/025/result.json"
parameter_size = 3
progress_file = "Generated/d_predprey1/025/progress.json"
random_state = 0x940e9692134cafa2
scratch_size = 12
