data_file = "ode-strogatz/d_vdp2.txt"
lambda_op = 1.0e-6
log_file = "Generated/d_vdp2/006/log.txt"
max_generations = 25
max_time = 300
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/d_vdp2/006/result.json"
progress_file = "Generated/d_vdp2/006/progress.json"
random_state = 0x9919c1f027e4d551
scratch_size = 12
