random_state = 0x371e970865fa4d31
num_samples = 32
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig"
output_size = 12
scratch_size = 12
parameter_size = 3
num_time_steps = 4
max_generations = 25
max_time = 3600
lambda_b = 1.0e-12
lambda_p = 1.0e-12
lambda_op = 1.0e-12
simplify = true
num_to_keep = 25
num_to_generate = 75
p_take_better = 0.65
p_take_very_best = 0.05
p_mutate_op = 0.15
p_mutate_index = 0.15
p_duplicate_index = 0.03
p_delete_index = 0.03
p_duplicate_instruction = 0.015
p_delete_instruction = 0.015
p_hop_instruction = 0.015
