random_state = 0x59f626bad27de798
num_samples = 32
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output_size = 12
scratch_size = 12
parameter_size = 3
num_time_steps = 4
max_generations = 25
max_time = 300
lambda_b = 1.0e-12
lambda_p = 1.0e-12
lambda_op = 1.0e-12
simplify = true
p_take_very_best = 0.05
