random_state = 0x59f626bad27de798
num_samples = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
scratch_size = 12
num_time_steps = 3
max_generations = 25
max_time = 3600
lambda_op = 1.0e-6
