random_state = 0xdf91f5527aea062b
num_samples = 32
op_inventory = "RationalFunction"
output_size = 12
scratch_size = 12
parameter_size = 3
num_time_steps = 4
max_generations = 100
max_time = 3600
lambda_op = 1.0e-10
num_to_keep = 50
num_to_generate = 150
p_take_very_best = 0.05
