data_file = "Things-to-bench/cosmo_data/C1d.csv"
lambda_op = 1.0e-6
log_file = "Generated/C1d/004/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_column = "target"
output_file = "Generated/C1d/004/result.json"
parameter_size = 3
progress_file = "Generated/C1d/004/progress.json"
random_state = 0xff522145d50ada62
random_subset_count = 1000
scratch_size = 12
