data_file = "Things-to-bench/datasets/F1.csv"
lambda_op = 1.0e-6
log_file = "Generated/F1/018/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/F1/018/result.json"
progress_file = "Generated/F1/018/progress.json"
random_state = 0x736218f116d8744d
scratch_size = 12
