data_file = "Things-to-bench/datasets/F2.csv"
lambda_op = 1.0e-6
log_file = "Generated/F2/032/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_column = "target"
output_file = "Generated/F2/032/result.json"
progress_file = "Generated/F2/032/progress.json"
random_state = 0x0ca4cf6e75835e80
scratch_size = 12
