data_file = "Things-to-bench/datasets/F3.csv"
lambda_op = 1.0e-6
log_file = "Generated/F3/031/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_column = "target"
output_file = "Generated/F3/031/result.json"
parameter_size = 3
progress_file = "Generated/F3/031/progress.json"
random_state = 0xd331cb7bc502f9b6
random_subset_count = 1000
scratch_size = 12
