data_file = "Things-to-bench/datasets/F3.csv"
lambda_op = 1.0e-6
log_file = "Generated/F3/015/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_column = "target"
output_file = "Generated/F3/015/result.json"
parameter_size = 3
progress_file = "Generated/F3/015/progress.json"
random_state = 0xa55bd51d303b9154
scratch_size = 12
