data_file = "Things-to-bench/datasets/F5.csv"
lambda_op = 1.0e-6
log_file = "Generated/F5/028/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_file = "Generated/F5/028/result.json"
progress_file = "Generated/F5/028/progress.json"
random_state = 0x190ffd9b0105f9ca
scratch_size = 12
