data_file = "Things-to-bench/datasets/F8.csv"
lambda_op = 1.0e-6
log_file = "Generated/F8/012/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output-size = 12
output_column = "target"
output_file = "Generated/F8/012/result.json"
parameter_size = 3
progress_file = "Generated/F8/012/progress.json"
random_state = 0x21c1aa73e9f79fe9
random_subset_count = 1000
scratch_size = 12
