data_file = "Things-to-bench/cosmo_data/C3g.csv"
lambda_op = 1.0e-6
log_file = "Generated/2026-06-16-2230/C3g/009/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output_column = "target"
output_file = "Generated/2026-06-16-2230/C3g/009/result.json"
output_size = 12
parameter_size = 3
progress_file = "Generated/2026-06-16-2230/C3g/009/progress.json"
random_state = 0x1bfa2d8c16ce48ba
random_subset_count = 1000
scratch_size = 12
