data_file = "Things-to-bench/datasets/F4.csv"
lambda_op = 1.0e-6
log_file = "Generated/2026-06-16-2230/F4/016/log.txt"
max_generations = 25
max_time = 3600
num_time_steps = 4
op_inventory = "Polynomial; RationalFunction; ExpLog; Trig; Hyperbolic"
output_column = "target"
output_file = "Generated/2026-06-16-2230/F4/016/result.json"
output_size = 12
parameter_size = 3
progress_file = "Generated/2026-06-16-2230/F4/016/progress.json"
random_state = 0x76245794a02547bc
random_subset_count = 1000
scratch_size = 12
